---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
spec:
  capacity: 
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-0497d3081f17a8f56
    fsType: ext4
